package com.woniu.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.woniu.entity.Administrative;
import com.woniu.entity.AdministrativeExample;
import com.woniu.entity.Hospital;

public interface AdministrativeMapper {
//	根据科室aid查找医院名称 
    List<String> findByAid(Integer aid);
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int countByExample(AdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByExample(AdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insert(Administrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insertSelective(Administrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    List<Administrative> selectByExample(AdministrativeExample example,RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    Administrative selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Administrative record, @Param("example") AdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExample(@Param("record") Administrative record, @Param("example") AdministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKeySelective(Administrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKey(Administrative record);
}