package com.woniu.mapper;

import com.woniu.entity.Bed;
import com.woniu.entity.BedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BedMapper {
	//查找医院下所有床的id
	List<Integer> selectByHid(Integer hid);
	//根据医院和科室查找床的id  注意，这个返回的list是床的id不是床的对象
	List<Integer> selectByHandA(Integer hid,Integer aid);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	int countByExample(BedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int deleteByExample(BedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int deleteByPrimaryKey(Integer bid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int insert(Bed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int insertSelective(Bed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	List<Bed> selectByExample(BedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	Bed selectByPrimaryKey(Integer bid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Bed record, @Param("example") BedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int updateByExample(@Param("record") Bed record, @Param("example") BedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int updateByPrimaryKeySelective(Bed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	int updateByPrimaryKey(Bed record);

}