package com.woniu.mapper;

import com.woniu.entity.Fixer;
import com.woniu.entity.FixerExample;
import com.woniu.entity.FixerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FixerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int countByExample(FixerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByExample(FixerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByPrimaryKey(FixerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insert(Fixer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insertSelective(Fixer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    List<Fixer> selectByExample(FixerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    Fixer selectByPrimaryKey(FixerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fixer record, @Param("example") FixerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExample(@Param("record") Fixer record, @Param("example") FixerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKeySelective(Fixer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKey(Fixer record);
}