package com.woniu.mapper;

import com.woniu.entity.Fixitem;
import com.woniu.entity.FixitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FixitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int countByExample(FixitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByExample(FixitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insert(Fixitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insertSelective(Fixitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    List<Fixitem> selectByExample(FixitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    Fixitem selectByPrimaryKey(Integer fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fixitem record, @Param("example") FixitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExample(@Param("record") Fixitem record, @Param("example") FixitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKeySelective(Fixitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fixitem
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKey(Fixitem record);
}