package com.woniu.mapper;

import com.woniu.entity.Hospitaladministrative;
import com.woniu.entity.HospitaladministrativeExample;
import com.woniu.entity.HospitaladministrativeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitaladministrativeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int countByExample(HospitaladministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByExample(HospitaladministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByPrimaryKey(HospitaladministrativeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insert(Hospitaladministrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insertSelective(Hospitaladministrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    List<Hospitaladministrative> selectByExample(HospitaladministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    Hospitaladministrative selectByPrimaryKey(HospitaladministrativeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hospitaladministrative record, @Param("example") HospitaladministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExample(@Param("record") Hospitaladministrative record, @Param("example") HospitaladministrativeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKeySelective(Hospitaladministrative record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitaladministrative
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKey(Hospitaladministrative record);
}