package com.woniu.mapper;

import com.woniu.entity.Hospitalmanger;
import com.woniu.entity.HospitalmangerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalmangerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int countByExample(HospitalmangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByExample(HospitalmangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insert(Hospitalmanger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insertSelective(Hospitalmanger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    List<Hospitalmanger> selectByExample(HospitalmangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    Hospitalmanger selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hospitalmanger record, @Param("example") HospitalmangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExample(@Param("record") Hospitalmanger record, @Param("example") HospitalmangerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKeySelective(Hospitalmanger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospitalmanger
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKey(Hospitalmanger record);
}