package com.woniu.mapper;

import com.woniu.entity.Scrap;
import com.woniu.entity.ScrapExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScrapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int countByExample(ScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByExample(ScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insert(Scrap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insertSelective(Scrap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    List<Scrap> selectByExample(ScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    Scrap selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Scrap record, @Param("example") ScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExample(@Param("record") Scrap record, @Param("example") ScrapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKeySelective(Scrap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scrap
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKey(Scrap record);
}