package com.woniu.mapper;

import com.woniu.entity.Shareholder;
import com.woniu.entity.ShareholderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShareholderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int countByExample(ShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByExample(ShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insert(Shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int insertSelective(Shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    List<Shareholder> selectByExample(ShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    Shareholder selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") Shareholder record, @Param("example") ShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByExample(@Param("record") Shareholder record, @Param("example") ShareholderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKeySelective(Shareholder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shareholder
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    int updateByPrimaryKey(Shareholder record);
}