server: 
  port: 1111 

spring: 
  mvc: 
    view: 
      prefix: /
      suffix: .jsp 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jiapei?characterEncoding=utf-8
    username: root
    password: 
     
logging: 
  level: 
    com: 
      woniu: 
        mapper: DEBUG

