server: 
  port: 9000 

spring: 
  mvc: 
    view: 
      prefix: /
      suffix: .jsp 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.31.86:3306/prj1?characterEncoding=utf-8
    username: prj1
    password: '#@$*()#$'
     
logging: 
  level: 
    com: 
      woniu: 
        mapper: DEBUG

#配置上传文件的最大值
servlet:
  multipart:
    max-file-size: 5Mb
    max-request-size: 50Mb
#自定义文件上传路径
web:
  upload-path: /upload    
    
