package com.woniu.entity;

import java.util.List;

public class Administrative {
   private List hospitals;
   
		public List getHospitals() {
			return hospitals;
		}

		public void setHospitals(List hospitals) {
			this.hospitals = hospitals;
		}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrative.aid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrative.aname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrative.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrative.aid
     *
     * @return the value of administrative.aid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrative.aid
     *
     * @param aid the value for administrative.aid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrative.aname
     *
     * @return the value of administrative.aname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrative.aname
     *
     * @param aname the value for administrative.aname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrative.isdelete
     *
     * @return the value of administrative.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrative.isdelete
     *
     * @param isdelete the value for administrative.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}