package com.woniu.entity;

public class Bed {
	@Override
	public String toString() {
		return "Bed [factory=" + factory + ", bid=" + bid + ", fid=" + fid + ", uid=" + uid + ", bnum=" + bnum
				+ ", productorconnectname=" + productorconnectname + ", bstatus=" + bstatus + ", istrouble=" + istrouble
				+ ", isdelete=" + isdelete + ", fkid=" + fkid + "]";
	}
	private Hospitaladministrative hospitaiAdministrative;
	
	public Hospitaladministrative getHospitaiAdministrative() {
		return hospitaiAdministrative;
	}

	public void setHospitaiAdministrative(Hospitaladministrative hospitaiAdministrative) {
		this.hospitaiAdministrative = hospitaiAdministrative;
	}
	private Factory factory;
	
	public Factory getFactory() {
		return factory;
	}

	public void setFactory(Factory factory) {
		this.factory = factory;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.bid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private Integer bid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.fid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private Integer fid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.uid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.bnum
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private String bnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.productorconnectname
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private String productorconnectname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.bstatus
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private Boolean bstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.istrouble
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private Boolean istrouble;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.isdelete
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private Integer isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bed.fkid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	private String fkid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.bid
	 * @return  the value of bed.bid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public Integer getBid() {
		return bid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.bid
	 * @param bid  the value for bed.bid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setBid(Integer bid) {
		this.bid = bid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.fid
	 * @return  the value of bed.fid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public Integer getFid() {
		return fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.fid
	 * @param fid  the value for bed.fid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setFid(Integer fid) {
		this.fid = fid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.uid
	 * @return  the value of bed.uid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.uid
	 * @param uid  the value for bed.uid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.bnum
	 * @return  the value of bed.bnum
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public String getBnum() {
		return bnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.bnum
	 * @param bnum  the value for bed.bnum
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setBnum(String bnum) {
		this.bnum = bnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.productorconnectname
	 * @return  the value of bed.productorconnectname
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public String getProductorconnectname() {
		return productorconnectname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.productorconnectname
	 * @param productorconnectname  the value for bed.productorconnectname
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setProductorconnectname(String productorconnectname) {
		this.productorconnectname = productorconnectname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.bstatus
	 * @return  the value of bed.bstatus
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public Boolean getBstatus() {
		return bstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.bstatus
	 * @param bstatus  the value for bed.bstatus
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setBstatus(Boolean bstatus) {
		this.bstatus = bstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.istrouble
	 * @return  the value of bed.istrouble
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public Boolean getIstrouble() {
		return istrouble;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.istrouble
	 * @param istrouble  the value for bed.istrouble
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setIstrouble(Boolean istrouble) {
		this.istrouble = istrouble;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.isdelete
	 * @return  the value of bed.isdelete
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public Integer getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.isdelete
	 * @param isdelete  the value for bed.isdelete
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setIsdelete(Integer isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.fkid
	 * @return  the value of bed.fkid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public String getFkid() {
		return fkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bed.fkid
	 * @param fkid  the value for bed.fkid
	 * @mbggenerated  Wed Aug 21 17:28:08 CST 2019
	 */
	public void setFkid(String fkid) {
		this.fkid = fkid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.productor
	 * @return  the value of bed.productor
	 * @mbggenerated  Wed Aug 21 17:22:49 CST 2019
	 */

	

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bed.productorphone
	 * @return  the value of bed.productorphone
	 * @mbggenerated  Wed Aug 21 17:22:49 CST 2019
	 */

	
}