package com.woniu.entity;

import java.util.ArrayList;
import java.util.List;

public class BedExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public BedExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBidIsNull() {
			addCriterion("bid is null");
			return (Criteria) this;
		}

		public Criteria andBidIsNotNull() {
			addCriterion("bid is not null");
			return (Criteria) this;
		}

		public Criteria andBidEqualTo(Integer value) {
			addCriterion("bid =", value, "bid");
			return (Criteria) this;
		}

		public Criteria andBidNotEqualTo(Integer value) {
			addCriterion("bid <>", value, "bid");
			return (Criteria) this;
		}

		public Criteria andBidGreaterThan(Integer value) {
			addCriterion("bid >", value, "bid");
			return (Criteria) this;
		}

		public Criteria andBidGreaterThanOrEqualTo(Integer value) {
			addCriterion("bid >=", value, "bid");
			return (Criteria) this;
		}

		public Criteria andBidLessThan(Integer value) {
			addCriterion("bid <", value, "bid");
			return (Criteria) this;
		}

		public Criteria andBidLessThanOrEqualTo(Integer value) {
			addCriterion("bid <=", value, "bid");
			return (Criteria) this;
		}

		public Criteria andBidIn(List<Integer> values) {
			addCriterion("bid in", values, "bid");
			return (Criteria) this;
		}

		public Criteria andBidNotIn(List<Integer> values) {
			addCriterion("bid not in", values, "bid");
			return (Criteria) this;
		}

		public Criteria andBidBetween(Integer value1, Integer value2) {
			addCriterion("bid between", value1, value2, "bid");
			return (Criteria) this;
		}

		public Criteria andBidNotBetween(Integer value1, Integer value2) {
			addCriterion("bid not between", value1, value2, "bid");
			return (Criteria) this;
		}

		public Criteria andFidIsNull() {
			addCriterion("fid is null");
			return (Criteria) this;
		}

		public Criteria andFidIsNotNull() {
			addCriterion("fid is not null");
			return (Criteria) this;
		}

		public Criteria andFidEqualTo(Integer value) {
			addCriterion("fid =", value, "fid");
			return (Criteria) this;
		}

		public Criteria andFidNotEqualTo(Integer value) {
			addCriterion("fid <>", value, "fid");
			return (Criteria) this;
		}

		public Criteria andFidGreaterThan(Integer value) {
			addCriterion("fid >", value, "fid");
			return (Criteria) this;
		}

		public Criteria andFidGreaterThanOrEqualTo(Integer value) {
			addCriterion("fid >=", value, "fid");
			return (Criteria) this;
		}

		public Criteria andFidLessThan(Integer value) {
			addCriterion("fid <", value, "fid");
			return (Criteria) this;
		}

		public Criteria andFidLessThanOrEqualTo(Integer value) {
			addCriterion("fid <=", value, "fid");
			return (Criteria) this;
		}

		public Criteria andFidIn(List<Integer> values) {
			addCriterion("fid in", values, "fid");
			return (Criteria) this;
		}

		public Criteria andFidNotIn(List<Integer> values) {
			addCriterion("fid not in", values, "fid");
			return (Criteria) this;
		}

		public Criteria andFidBetween(Integer value1, Integer value2) {
			addCriterion("fid between", value1, value2, "fid");
			return (Criteria) this;
		}

		public Criteria andFidNotBetween(Integer value1, Integer value2) {
			addCriterion("fid not between", value1, value2, "fid");
			return (Criteria) this;
		}

		public Criteria andUidIsNull() {
			addCriterion("uid is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("uid is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(Integer value) {
			addCriterion("uid =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(Integer value) {
			addCriterion("uid <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(Integer value) {
			addCriterion("uid >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(Integer value) {
			addCriterion("uid >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(Integer value) {
			addCriterion("uid <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(Integer value) {
			addCriterion("uid <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<Integer> values) {
			addCriterion("uid in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<Integer> values) {
			addCriterion("uid not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(Integer value1, Integer value2) {
			addCriterion("uid between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(Integer value1, Integer value2) {
			addCriterion("uid not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andHidIsNull() {
			addCriterion("hid is null");
			return (Criteria) this;
		}

		public Criteria andHidIsNotNull() {
			addCriterion("hid is not null");
			return (Criteria) this;
		}

		public Criteria andHidEqualTo(Integer value) {
			addCriterion("hid =", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotEqualTo(Integer value) {
			addCriterion("hid <>", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidGreaterThan(Integer value) {
			addCriterion("hid >", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidGreaterThanOrEqualTo(Integer value) {
			addCriterion("hid >=", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidLessThan(Integer value) {
			addCriterion("hid <", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidLessThanOrEqualTo(Integer value) {
			addCriterion("hid <=", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidIn(List<Integer> values) {
			addCriterion("hid in", values, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotIn(List<Integer> values) {
			addCriterion("hid not in", values, "hid");
			return (Criteria) this;
		}

		public Criteria andHidBetween(Integer value1, Integer value2) {
			addCriterion("hid between", value1, value2, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotBetween(Integer value1, Integer value2) {
			addCriterion("hid not between", value1, value2, "hid");
			return (Criteria) this;
		}

		public Criteria andAidIsNull() {
			addCriterion("aid is null");
			return (Criteria) this;
		}

		public Criteria andAidIsNotNull() {
			addCriterion("aid is not null");
			return (Criteria) this;
		}

		public Criteria andAidEqualTo(Integer value) {
			addCriterion("aid =", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidNotEqualTo(Integer value) {
			addCriterion("aid <>", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidGreaterThan(Integer value) {
			addCriterion("aid >", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidGreaterThanOrEqualTo(Integer value) {
			addCriterion("aid >=", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidLessThan(Integer value) {
			addCriterion("aid <", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidLessThanOrEqualTo(Integer value) {
			addCriterion("aid <=", value, "aid");
			return (Criteria) this;
		}

		public Criteria andAidIn(List<Integer> values) {
			addCriterion("aid in", values, "aid");
			return (Criteria) this;
		}

		public Criteria andAidNotIn(List<Integer> values) {
			addCriterion("aid not in", values, "aid");
			return (Criteria) this;
		}

		public Criteria andAidBetween(Integer value1, Integer value2) {
			addCriterion("aid between", value1, value2, "aid");
			return (Criteria) this;
		}

		public Criteria andAidNotBetween(Integer value1, Integer value2) {
			addCriterion("aid not between", value1, value2, "aid");
			return (Criteria) this;
		}

		public Criteria andBnumIsNull() {
			addCriterion("bnum is null");
			return (Criteria) this;
		}

		public Criteria andBnumIsNotNull() {
			addCriterion("bnum is not null");
			return (Criteria) this;
		}

		public Criteria andBnumEqualTo(String value) {
			addCriterion("bnum =", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumNotEqualTo(String value) {
			addCriterion("bnum <>", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumGreaterThan(String value) {
			addCriterion("bnum >", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumGreaterThanOrEqualTo(String value) {
			addCriterion("bnum >=", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumLessThan(String value) {
			addCriterion("bnum <", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumLessThanOrEqualTo(String value) {
			addCriterion("bnum <=", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumLike(String value) {
			addCriterion("bnum like", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumNotLike(String value) {
			addCriterion("bnum not like", value, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumIn(List<String> values) {
			addCriterion("bnum in", values, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumNotIn(List<String> values) {
			addCriterion("bnum not in", values, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumBetween(String value1, String value2) {
			addCriterion("bnum between", value1, value2, "bnum");
			return (Criteria) this;
		}

		public Criteria andBnumNotBetween(String value1, String value2) {
			addCriterion("bnum not between", value1, value2, "bnum");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameIsNull() {
			addCriterion("productorconnectname is null");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameIsNotNull() {
			addCriterion("productorconnectname is not null");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameEqualTo(String value) {
			addCriterion("productorconnectname =", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameNotEqualTo(String value) {
			addCriterion("productorconnectname <>", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameGreaterThan(String value) {
			addCriterion("productorconnectname >", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameGreaterThanOrEqualTo(String value) {
			addCriterion("productorconnectname >=", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameLessThan(String value) {
			addCriterion("productorconnectname <", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameLessThanOrEqualTo(String value) {
			addCriterion("productorconnectname <=", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameLike(String value) {
			addCriterion("productorconnectname like", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameNotLike(String value) {
			addCriterion("productorconnectname not like", value, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameIn(List<String> values) {
			addCriterion("productorconnectname in", values, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameNotIn(List<String> values) {
			addCriterion("productorconnectname not in", values, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameBetween(String value1, String value2) {
			addCriterion("productorconnectname between", value1, value2, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andProductorconnectnameNotBetween(String value1, String value2) {
			addCriterion("productorconnectname not between", value1, value2, "productorconnectname");
			return (Criteria) this;
		}

		public Criteria andBstatusIsNull() {
			addCriterion("bstatus is null");
			return (Criteria) this;
		}

		public Criteria andBstatusIsNotNull() {
			addCriterion("bstatus is not null");
			return (Criteria) this;
		}

		public Criteria andBstatusEqualTo(Boolean value) {
			addCriterion("bstatus =", value, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusNotEqualTo(Boolean value) {
			addCriterion("bstatus <>", value, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusGreaterThan(Boolean value) {
			addCriterion("bstatus >", value, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusGreaterThanOrEqualTo(Boolean value) {
			addCriterion("bstatus >=", value, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusLessThan(Boolean value) {
			addCriterion("bstatus <", value, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusLessThanOrEqualTo(Boolean value) {
			addCriterion("bstatus <=", value, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusIn(List<Boolean> values) {
			addCriterion("bstatus in", values, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusNotIn(List<Boolean> values) {
			addCriterion("bstatus not in", values, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusBetween(Boolean value1, Boolean value2) {
			addCriterion("bstatus between", value1, value2, "bstatus");
			return (Criteria) this;
		}

		public Criteria andBstatusNotBetween(Boolean value1, Boolean value2) {
			addCriterion("bstatus not between", value1, value2, "bstatus");
			return (Criteria) this;
		}

		public Criteria andIstroubleIsNull() {
			addCriterion("istrouble is null");
			return (Criteria) this;
		}

		public Criteria andIstroubleIsNotNull() {
			addCriterion("istrouble is not null");
			return (Criteria) this;
		}

		public Criteria andIstroubleEqualTo(Boolean value) {
			addCriterion("istrouble =", value, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleNotEqualTo(Boolean value) {
			addCriterion("istrouble <>", value, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleGreaterThan(Boolean value) {
			addCriterion("istrouble >", value, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleGreaterThanOrEqualTo(Boolean value) {
			addCriterion("istrouble >=", value, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleLessThan(Boolean value) {
			addCriterion("istrouble <", value, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleLessThanOrEqualTo(Boolean value) {
			addCriterion("istrouble <=", value, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleIn(List<Boolean> values) {
			addCriterion("istrouble in", values, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleNotIn(List<Boolean> values) {
			addCriterion("istrouble not in", values, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleBetween(Boolean value1, Boolean value2) {
			addCriterion("istrouble between", value1, value2, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIstroubleNotBetween(Boolean value1, Boolean value2) {
			addCriterion("istrouble not between", value1, value2, "istrouble");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIsNull() {
			addCriterion("isdelete is null");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIsNotNull() {
			addCriterion("isdelete is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeleteEqualTo(Integer value) {
			addCriterion("isdelete =", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotEqualTo(Integer value) {
			addCriterion("isdelete <>", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteGreaterThan(Integer value) {
			addCriterion("isdelete >", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
			addCriterion("isdelete >=", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteLessThan(Integer value) {
			addCriterion("isdelete <", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
			addCriterion("isdelete <=", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIn(List<Integer> values) {
			addCriterion("isdelete in", values, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotIn(List<Integer> values) {
			addCriterion("isdelete not in", values, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
			addCriterion("isdelete between", value1, value2, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
			addCriterion("isdelete not between", value1, value2, "isdelete");
			return (Criteria) this;
		}

		public Criteria andFkidIsNull() {
			addCriterion("fkid is null");
			return (Criteria) this;
		}

		public Criteria andFkidIsNotNull() {
			addCriterion("fkid is not null");
			return (Criteria) this;
		}

		public Criteria andFkidEqualTo(String value) {
			addCriterion("fkid =", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidNotEqualTo(String value) {
			addCriterion("fkid <>", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidGreaterThan(String value) {
			addCriterion("fkid >", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidGreaterThanOrEqualTo(String value) {
			addCriterion("fkid >=", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidLessThan(String value) {
			addCriterion("fkid <", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidLessThanOrEqualTo(String value) {
			addCriterion("fkid <=", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidLike(String value) {
			addCriterion("fkid like", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidNotLike(String value) {
			addCriterion("fkid not like", value, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidIn(List<String> values) {
			addCriterion("fkid in", values, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidNotIn(List<String> values) {
			addCriterion("fkid not in", values, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidBetween(String value1, String value2) {
			addCriterion("fkid between", value1, value2, "fkid");
			return (Criteria) this;
		}

		public Criteria andFkidNotBetween(String value1, String value2) {
			addCriterion("fkid not between", value1, value2, "fkid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bed
	 * @mbggenerated  Fri Aug 23 21:13:36 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bed
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:25:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}