package com.woniu.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCnameIsNull() {
            addCriterion("cname is null");
            return (Criteria) this;
        }

        public Criteria andCnameIsNotNull() {
            addCriterion("cname is not null");
            return (Criteria) this;
        }

        public Criteria andCnameEqualTo(String value) {
            addCriterion("cname =", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotEqualTo(String value) {
            addCriterion("cname <>", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThan(String value) {
            addCriterion("cname >", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThanOrEqualTo(String value) {
            addCriterion("cname >=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThan(String value) {
            addCriterion("cname <", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThanOrEqualTo(String value) {
            addCriterion("cname <=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLike(String value) {
            addCriterion("cname like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotLike(String value) {
            addCriterion("cname not like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameIn(List<String> values) {
            addCriterion("cname in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotIn(List<String> values) {
            addCriterion("cname not in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameBetween(String value1, String value2) {
            addCriterion("cname between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotBetween(String value1, String value2) {
            addCriterion("cname not between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCpassIsNull() {
            addCriterion("cpass is null");
            return (Criteria) this;
        }

        public Criteria andCpassIsNotNull() {
            addCriterion("cpass is not null");
            return (Criteria) this;
        }

        public Criteria andCpassEqualTo(String value) {
            addCriterion("cpass =", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassNotEqualTo(String value) {
            addCriterion("cpass <>", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassGreaterThan(String value) {
            addCriterion("cpass >", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassGreaterThanOrEqualTo(String value) {
            addCriterion("cpass >=", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassLessThan(String value) {
            addCriterion("cpass <", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassLessThanOrEqualTo(String value) {
            addCriterion("cpass <=", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassLike(String value) {
            addCriterion("cpass like", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassNotLike(String value) {
            addCriterion("cpass not like", value, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassIn(List<String> values) {
            addCriterion("cpass in", values, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassNotIn(List<String> values) {
            addCriterion("cpass not in", values, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassBetween(String value1, String value2) {
            addCriterion("cpass between", value1, value2, "cpass");
            return (Criteria) this;
        }

        public Criteria andCpassNotBetween(String value1, String value2) {
            addCriterion("cpass not between", value1, value2, "cpass");
            return (Criteria) this;
        }

        public Criteria andCnicknameIsNull() {
            addCriterion("cnickname is null");
            return (Criteria) this;
        }

        public Criteria andCnicknameIsNotNull() {
            addCriterion("cnickname is not null");
            return (Criteria) this;
        }

        public Criteria andCnicknameEqualTo(String value) {
            addCriterion("cnickname =", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameNotEqualTo(String value) {
            addCriterion("cnickname <>", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameGreaterThan(String value) {
            addCriterion("cnickname >", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameGreaterThanOrEqualTo(String value) {
            addCriterion("cnickname >=", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameLessThan(String value) {
            addCriterion("cnickname <", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameLessThanOrEqualTo(String value) {
            addCriterion("cnickname <=", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameLike(String value) {
            addCriterion("cnickname like", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameNotLike(String value) {
            addCriterion("cnickname not like", value, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameIn(List<String> values) {
            addCriterion("cnickname in", values, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameNotIn(List<String> values) {
            addCriterion("cnickname not in", values, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameBetween(String value1, String value2) {
            addCriterion("cnickname between", value1, value2, "cnickname");
            return (Criteria) this;
        }

        public Criteria andCnicknameNotBetween(String value1, String value2) {
            addCriterion("cnickname not between", value1, value2, "cnickname");
            return (Criteria) this;
        }

        public Criteria andRegtimeIsNull() {
            addCriterion("regtime is null");
            return (Criteria) this;
        }

        public Criteria andRegtimeIsNotNull() {
            addCriterion("regtime is not null");
            return (Criteria) this;
        }

        public Criteria andRegtimeEqualTo(Date value) {
            addCriterion("regtime =", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotEqualTo(Date value) {
            addCriterion("regtime <>", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeGreaterThan(Date value) {
            addCriterion("regtime >", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("regtime >=", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeLessThan(Date value) {
            addCriterion("regtime <", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeLessThanOrEqualTo(Date value) {
            addCriterion("regtime <=", value, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeIn(List<Date> values) {
            addCriterion("regtime in", values, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotIn(List<Date> values) {
            addCriterion("regtime not in", values, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeBetween(Date value1, Date value2) {
            addCriterion("regtime between", value1, value2, "regtime");
            return (Criteria) this;
        }

        public Criteria andRegtimeNotBetween(Date value1, Date value2) {
            addCriterion("regtime not between", value1, value2, "regtime");
            return (Criteria) this;
        }

        public Criteria andIsdepositIsNull() {
            addCriterion("isdeposit is null");
            return (Criteria) this;
        }

        public Criteria andIsdepositIsNotNull() {
            addCriterion("isdeposit is not null");
            return (Criteria) this;
        }

        public Criteria andIsdepositEqualTo(Integer value) {
            addCriterion("isdeposit =", value, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositNotEqualTo(Integer value) {
            addCriterion("isdeposit <>", value, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositGreaterThan(Integer value) {
            addCriterion("isdeposit >", value, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositGreaterThanOrEqualTo(Integer value) {
            addCriterion("isdeposit >=", value, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositLessThan(Integer value) {
            addCriterion("isdeposit <", value, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositLessThanOrEqualTo(Integer value) {
            addCriterion("isdeposit <=", value, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositIn(List<Integer> values) {
            addCriterion("isdeposit in", values, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositNotIn(List<Integer> values) {
            addCriterion("isdeposit not in", values, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositBetween(Integer value1, Integer value2) {
            addCriterion("isdeposit between", value1, value2, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andIsdepositNotBetween(Integer value1, Integer value2) {
            addCriterion("isdeposit not between", value1, value2, "isdeposit");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(BigDecimal value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(BigDecimal value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(BigDecimal value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(BigDecimal value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<BigDecimal> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<BigDecimal> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andOrdertimesIsNull() {
            addCriterion("ordertimes is null");
            return (Criteria) this;
        }

        public Criteria andOrdertimesIsNotNull() {
            addCriterion("ordertimes is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertimesEqualTo(Integer value) {
            addCriterion("ordertimes =", value, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesNotEqualTo(Integer value) {
            addCriterion("ordertimes <>", value, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesGreaterThan(Integer value) {
            addCriterion("ordertimes >", value, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordertimes >=", value, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesLessThan(Integer value) {
            addCriterion("ordertimes <", value, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesLessThanOrEqualTo(Integer value) {
            addCriterion("ordertimes <=", value, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesIn(List<Integer> values) {
            addCriterion("ordertimes in", values, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesNotIn(List<Integer> values) {
            addCriterion("ordertimes not in", values, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesBetween(Integer value1, Integer value2) {
            addCriterion("ordertimes between", value1, value2, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andOrdertimesNotBetween(Integer value1, Integer value2) {
            addCriterion("ordertimes not between", value1, value2, "ordertimes");
            return (Criteria) this;
        }

        public Criteria andSumconsumeIsNull() {
            addCriterion("sumconsume is null");
            return (Criteria) this;
        }

        public Criteria andSumconsumeIsNotNull() {
            addCriterion("sumconsume is not null");
            return (Criteria) this;
        }

        public Criteria andSumconsumeEqualTo(Integer value) {
            addCriterion("sumconsume =", value, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeNotEqualTo(Integer value) {
            addCriterion("sumconsume <>", value, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeGreaterThan(Integer value) {
            addCriterion("sumconsume >", value, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("sumconsume >=", value, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeLessThan(Integer value) {
            addCriterion("sumconsume <", value, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeLessThanOrEqualTo(Integer value) {
            addCriterion("sumconsume <=", value, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeIn(List<Integer> values) {
            addCriterion("sumconsume in", values, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeNotIn(List<Integer> values) {
            addCriterion("sumconsume not in", values, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeBetween(Integer value1, Integer value2) {
            addCriterion("sumconsume between", value1, value2, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andSumconsumeNotBetween(Integer value1, Integer value2) {
            addCriterion("sumconsume not between", value1, value2, "sumconsume");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isdelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isdelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isdelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isdelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isdelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isdelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isdelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isdelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isdelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isdelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isdelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isdelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:25:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}