package com.woniu.entity;

public class Factory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.fname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String fname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column factory.address
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.fid
     *
     * @return the value of factory.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.fid
     *
     * @param fid the value for factory.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.fname
     *
     * @return the value of factory.fname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.fname
     *
     * @param fname the value for factory.fname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setFname(String fname) {
        this.fname = fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.phone
     *
     * @return the value of factory.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.phone
     *
     * @param phone the value for factory.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column factory.address
     *
     * @return the value of factory.address
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column factory.address
     *
     * @param address the value for factory.address
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }
}