package com.woniu.entity;

import java.util.Date;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.content
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.photo
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.time
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.fid
     *
     * @return the value of feedback.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.fid
     *
     * @param fid the value for feedback.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.content
     *
     * @return the value of feedback.content
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.content
     *
     * @param content the value for feedback.content
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.photo
     *
     * @return the value of feedback.photo
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.photo
     *
     * @param photo the value for feedback.photo
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.phone
     *
     * @return the value of feedback.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.phone
     *
     * @param phone the value for feedback.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.time
     *
     * @return the value of feedback.time
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.time
     *
     * @param time the value for feedback.time
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.isdelete
     *
     * @return the value of feedback.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.isdelete
     *
     * @param isdelete the value for feedback.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}