package com.woniu.entity;

public class Fixer extends FixerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixer.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixer.isdelete
     *
     * @return the value of fixer.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixer.isdelete
     *
     * @param isdelete the value for fixer.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}