package com.woniu.entity;

public class FixerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixer.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixer.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixer.hid
     *
     * @return the value of fixer.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixer.hid
     *
     * @param hid the value for fixer.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixer.uid
     *
     * @return the value of fixer.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixer.uid
     *
     * @param uid the value for fixer.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}