package com.woniu.entity;

import java.util.Date;

public class Fixitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixitem.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixitem.ftime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Date ftime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixitem.tid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixitem.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixitem.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fixitem.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixitem.fid
     *
     * @return the value of fixitem.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixitem.fid
     *
     * @param fid the value for fixitem.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixitem.ftime
     *
     * @return the value of fixitem.ftime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Date getFtime() {
        return ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixitem.ftime
     *
     * @param ftime the value for fixitem.ftime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setFtime(Date ftime) {
        this.ftime = ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixitem.tid
     *
     * @return the value of fixitem.tid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixitem.tid
     *
     * @param tid the value for fixitem.tid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixitem.uid
     *
     * @return the value of fixitem.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixitem.uid
     *
     * @param uid the value for fixitem.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixitem.hid
     *
     * @return the value of fixitem.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixitem.hid
     *
     * @param hid the value for fixitem.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fixitem.isdelete
     *
     * @return the value of fixitem.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fixitem.isdelete
     *
     * @param isdelete the value for fixitem.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}