package com.woniu.entity;

import java.util.List;

public class Hospital {
	
	private List<Administrative> administrative;
    @Override
	public String toString() {
		return "Hospital [hid=" + hid + ", hname=" + hname + ", province=" + province + ", city=" + city + ", zone="
				+ zone + ", country=" + country + ", rent=" + rent + ", account=" + account + ", isdelete=" + isdelete
				+ "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String hname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.province
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.city
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.zone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String zone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.country
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.rent
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Double rent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.account
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hid
     *
     * @return the value of hospital.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hid
     *
     * @param hid the value for hospital.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hname
     *
     * @return the value of hospital.hname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hname
     *
     * @param hname the value for hospital.hname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setHname(String hname) {
        this.hname = hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.province
     *
     * @return the value of hospital.province
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.province
     *
     * @param province the value for hospital.province
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.city
     *
     * @return the value of hospital.city
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.city
     *
     * @param city the value for hospital.city
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.zone
     *
     * @return the value of hospital.zone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getZone() {
        return zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.zone
     *
     * @param zone the value for hospital.zone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.country
     *
     * @return the value of hospital.country
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.country
     *
     * @param country the value for hospital.country
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.rent
     *
     * @return the value of hospital.rent
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Double getRent() {
        return rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.rent
     *
     * @param rent the value for hospital.rent
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setRent(Double rent) {
        this.rent = rent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.account
     *
     * @return the value of hospital.account
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.account
     *
     * @param account the value for hospital.account
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.isdelete
     *
     * @return the value of hospital.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.isdelete
     *
     * @param isdelete the value for hospital.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}