package com.woniu.entity;

public class HospitaladministrativeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospitaladministrative.aid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospitaladministrative.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer hid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospitaladministrative.aid
     *
     * @return the value of hospitaladministrative.aid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospitaladministrative.aid
     *
     * @param aid the value for hospitaladministrative.aid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospitaladministrative.hid
     *
     * @return the value of hospitaladministrative.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospitaladministrative.hid
     *
     * @param hid the value for hospitaladministrative.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }
}