package com.woniu.entity;

import java.util.ArrayList;
import java.util.List;

public class HospitalExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public HospitalExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andHidIsNull() {
			addCriterion("hid is null");
			return (Criteria) this;
		}

		public Criteria andHidIsNotNull() {
			addCriterion("hid is not null");
			return (Criteria) this;
		}

		public Criteria andHidEqualTo(Integer value) {
			addCriterion("hid =", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotEqualTo(Integer value) {
			addCriterion("hid <>", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidGreaterThan(Integer value) {
			addCriterion("hid >", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidGreaterThanOrEqualTo(Integer value) {
			addCriterion("hid >=", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidLessThan(Integer value) {
			addCriterion("hid <", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidLessThanOrEqualTo(Integer value) {
			addCriterion("hid <=", value, "hid");
			return (Criteria) this;
		}

		public Criteria andHidIn(List<Integer> values) {
			addCriterion("hid in", values, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotIn(List<Integer> values) {
			addCriterion("hid not in", values, "hid");
			return (Criteria) this;
		}

		public Criteria andHidBetween(Integer value1, Integer value2) {
			addCriterion("hid between", value1, value2, "hid");
			return (Criteria) this;
		}

		public Criteria andHidNotBetween(Integer value1, Integer value2) {
			addCriterion("hid not between", value1, value2, "hid");
			return (Criteria) this;
		}

		public Criteria andHnameIsNull() {
			addCriterion("hname is null");
			return (Criteria) this;
		}

		public Criteria andHnameIsNotNull() {
			addCriterion("hname is not null");
			return (Criteria) this;
		}

		public Criteria andHnameEqualTo(String value) {
			addCriterion("hname =", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameNotEqualTo(String value) {
			addCriterion("hname <>", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameGreaterThan(String value) {
			addCriterion("hname >", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameGreaterThanOrEqualTo(String value) {
			addCriterion("hname >=", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameLessThan(String value) {
			addCriterion("hname <", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameLessThanOrEqualTo(String value) {
			addCriterion("hname <=", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameLike(String value) {
			addCriterion("hname like", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameNotLike(String value) {
			addCriterion("hname not like", value, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameIn(List<String> values) {
			addCriterion("hname in", values, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameNotIn(List<String> values) {
			addCriterion("hname not in", values, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameBetween(String value1, String value2) {
			addCriterion("hname between", value1, value2, "hname");
			return (Criteria) this;
		}

		public Criteria andHnameNotBetween(String value1, String value2) {
			addCriterion("hname not between", value1, value2, "hname");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("province is null");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("province is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("province =", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("province <>", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("province >", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("province >=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("province <", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("province <=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("province like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("province not like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceIn(List<String> values) {
			addCriterion("province in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotIn(List<String> values) {
			addCriterion("province not in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("province between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("province not between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andZoneIsNull() {
			addCriterion("zone is null");
			return (Criteria) this;
		}

		public Criteria andZoneIsNotNull() {
			addCriterion("zone is not null");
			return (Criteria) this;
		}

		public Criteria andZoneEqualTo(String value) {
			addCriterion("zone =", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneNotEqualTo(String value) {
			addCriterion("zone <>", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneGreaterThan(String value) {
			addCriterion("zone >", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneGreaterThanOrEqualTo(String value) {
			addCriterion("zone >=", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneLessThan(String value) {
			addCriterion("zone <", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneLessThanOrEqualTo(String value) {
			addCriterion("zone <=", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneLike(String value) {
			addCriterion("zone like", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneNotLike(String value) {
			addCriterion("zone not like", value, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneIn(List<String> values) {
			addCriterion("zone in", values, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneNotIn(List<String> values) {
			addCriterion("zone not in", values, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneBetween(String value1, String value2) {
			addCriterion("zone between", value1, value2, "zone");
			return (Criteria) this;
		}

		public Criteria andZoneNotBetween(String value1, String value2) {
			addCriterion("zone not between", value1, value2, "zone");
			return (Criteria) this;
		}

		public Criteria andCountryIsNull() {
			addCriterion("country is null");
			return (Criteria) this;
		}

		public Criteria andCountryIsNotNull() {
			addCriterion("country is not null");
			return (Criteria) this;
		}

		public Criteria andCountryEqualTo(String value) {
			addCriterion("country =", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotEqualTo(String value) {
			addCriterion("country <>", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThan(String value) {
			addCriterion("country >", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThanOrEqualTo(String value) {
			addCriterion("country >=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThan(String value) {
			addCriterion("country <", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThanOrEqualTo(String value) {
			addCriterion("country <=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLike(String value) {
			addCriterion("country like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotLike(String value) {
			addCriterion("country not like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryIn(List<String> values) {
			addCriterion("country in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotIn(List<String> values) {
			addCriterion("country not in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryBetween(String value1, String value2) {
			addCriterion("country between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotBetween(String value1, String value2) {
			addCriterion("country not between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andRentIsNull() {
			addCriterion("rent is null");
			return (Criteria) this;
		}

		public Criteria andRentIsNotNull() {
			addCriterion("rent is not null");
			return (Criteria) this;
		}

		public Criteria andRentEqualTo(Double value) {
			addCriterion("rent =", value, "rent");
			return (Criteria) this;
		}

		public Criteria andRentNotEqualTo(Double value) {
			addCriterion("rent <>", value, "rent");
			return (Criteria) this;
		}

		public Criteria andRentGreaterThan(Double value) {
			addCriterion("rent >", value, "rent");
			return (Criteria) this;
		}

		public Criteria andRentGreaterThanOrEqualTo(Double value) {
			addCriterion("rent >=", value, "rent");
			return (Criteria) this;
		}

		public Criteria andRentLessThan(Double value) {
			addCriterion("rent <", value, "rent");
			return (Criteria) this;
		}

		public Criteria andRentLessThanOrEqualTo(Double value) {
			addCriterion("rent <=", value, "rent");
			return (Criteria) this;
		}

		public Criteria andRentIn(List<Double> values) {
			addCriterion("rent in", values, "rent");
			return (Criteria) this;
		}

		public Criteria andRentNotIn(List<Double> values) {
			addCriterion("rent not in", values, "rent");
			return (Criteria) this;
		}

		public Criteria andRentBetween(Double value1, Double value2) {
			addCriterion("rent between", value1, value2, "rent");
			return (Criteria) this;
		}

		public Criteria andRentNotBetween(Double value1, Double value2) {
			addCriterion("rent not between", value1, value2, "rent");
			return (Criteria) this;
		}

		public Criteria andAccountIsNull() {
			addCriterion("account is null");
			return (Criteria) this;
		}

		public Criteria andAccountIsNotNull() {
			addCriterion("account is not null");
			return (Criteria) this;
		}

		public Criteria andAccountEqualTo(String value) {
			addCriterion("account =", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotEqualTo(String value) {
			addCriterion("account <>", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountGreaterThan(String value) {
			addCriterion("account >", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountGreaterThanOrEqualTo(String value) {
			addCriterion("account >=", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLessThan(String value) {
			addCriterion("account <", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLessThanOrEqualTo(String value) {
			addCriterion("account <=", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountLike(String value) {
			addCriterion("account like", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotLike(String value) {
			addCriterion("account not like", value, "account");
			return (Criteria) this;
		}

		public Criteria andAccountIn(List<String> values) {
			addCriterion("account in", values, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotIn(List<String> values) {
			addCriterion("account not in", values, "account");
			return (Criteria) this;
		}

		public Criteria andAccountBetween(String value1, String value2) {
			addCriterion("account between", value1, value2, "account");
			return (Criteria) this;
		}

		public Criteria andAccountNotBetween(String value1, String value2) {
			addCriterion("account not between", value1, value2, "account");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIsNull() {
			addCriterion("isdelete is null");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIsNotNull() {
			addCriterion("isdelete is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeleteEqualTo(Integer value) {
			addCriterion("isdelete =", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotEqualTo(Integer value) {
			addCriterion("isdelete <>", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteGreaterThan(Integer value) {
			addCriterion("isdelete >", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
			addCriterion("isdelete >=", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteLessThan(Integer value) {
			addCriterion("isdelete <", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
			addCriterion("isdelete <=", value, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteIn(List<Integer> values) {
			addCriterion("isdelete in", values, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotIn(List<Integer> values) {
			addCriterion("isdelete not in", values, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
			addCriterion("isdelete between", value1, value2, "isdelete");
			return (Criteria) this;
		}

		public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
			addCriterion("isdelete not between", value1, value2, "isdelete");
			return (Criteria) this;
		}

		public Criteria andHresperIsNull() {
			addCriterion("hresper is null");
			return (Criteria) this;
		}

		public Criteria andHresperIsNotNull() {
			addCriterion("hresper is not null");
			return (Criteria) this;
		}

		public Criteria andHresperEqualTo(String value) {
			addCriterion("hresper =", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperNotEqualTo(String value) {
			addCriterion("hresper <>", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperGreaterThan(String value) {
			addCriterion("hresper >", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperGreaterThanOrEqualTo(String value) {
			addCriterion("hresper >=", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperLessThan(String value) {
			addCriterion("hresper <", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperLessThanOrEqualTo(String value) {
			addCriterion("hresper <=", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperLike(String value) {
			addCriterion("hresper like", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperNotLike(String value) {
			addCriterion("hresper not like", value, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperIn(List<String> values) {
			addCriterion("hresper in", values, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperNotIn(List<String> values) {
			addCriterion("hresper not in", values, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperBetween(String value1, String value2) {
			addCriterion("hresper between", value1, value2, "hresper");
			return (Criteria) this;
		}

		public Criteria andHresperNotBetween(String value1, String value2) {
			addCriterion("hresper not between", value1, value2, "hresper");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table hospital
	 * @mbggenerated  Mon Aug 26 18:49:15 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hospital
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 19 15:25:36 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}