package com.woniu.entity;

public class Hospitalmanger {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospitalmanger.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospitalmanger.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer hid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospitalmanger.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospitalmanger.uid
     *
     * @return the value of hospitalmanger.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospitalmanger.uid
     *
     * @param uid the value for hospitalmanger.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospitalmanger.hid
     *
     * @return the value of hospitalmanger.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospitalmanger.hid
     *
     * @param hid the value for hospitalmanger.hid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospitalmanger.isdelete
     *
     * @return the value of hospitalmanger.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospitalmanger.isdelete
     *
     * @param isdelete the value for hospitalmanger.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}