package com.woniu.entity;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.lid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.area
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.content
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.ip
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.time
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.lid
     *
     * @return the value of log.lid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.lid
     *
     * @param lid the value for log.lid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operator
     *
     * @return the value of log.operator
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operator
     *
     * @param operator the value for log.operator
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.area
     *
     * @return the value of log.area
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.area
     *
     * @param area the value for log.area
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.content
     *
     * @return the value of log.content
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.content
     *
     * @param content the value for log.content
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.ip
     *
     * @return the value of log.ip
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.ip
     *
     * @param ip the value for log.ip
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.time
     *
     * @return the value of log.time
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.time
     *
     * @param time the value for log.time
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.isdelete
     *
     * @return the value of log.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.isdelete
     *
     * @param isdelete the value for log.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}