package com.woniu.entity;

import java.util.Date;

public class Orders {
	private Bed bed;
	
    public Bed getBed() {
		return bed;
	}

	public void setBed(Bed bed) {
		this.bed = bed;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.oid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.onum
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String onum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.bid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actualpay
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Double actualpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paystatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordertime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.returntime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Date returntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.isunusual
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isunusual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.unusualtype
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String unusualtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paytime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderstatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.oid
     *
     * @return the value of orders.oid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.oid
     *
     * @param oid the value for orders.oid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.onum
     *
     * @return the value of orders.onum
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getOnum() {
        return onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.onum
     *
     * @param onum the value for orders.onum
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setOnum(String onum) {
        this.onum = onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.bid
     *
     * @return the value of orders.bid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.bid
     *
     * @param bid the value for orders.bid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actualpay
     *
     * @return the value of orders.actualpay
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Double getActualpay() {
        return actualpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actualpay
     *
     * @param actualpay the value for orders.actualpay
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setActualpay(Double actualpay) {
        this.actualpay = actualpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paystatus
     *
     * @return the value of orders.paystatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paystatus
     *
     * @param paystatus the value for orders.paystatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordertime
     *
     * @return the value of orders.ordertime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordertime
     *
     * @param ordertime the value for orders.ordertime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.returntime
     *
     * @return the value of orders.returntime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Date getReturntime() {
        return returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.returntime
     *
     * @param returntime the value for orders.returntime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setReturntime(Date returntime) {
        this.returntime = returntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.isunusual
     *
     * @return the value of orders.isunusual
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsunusual() {
        return isunusual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.isunusual
     *
     * @param isunusual the value for orders.isunusual
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsunusual(Integer isunusual) {
        this.isunusual = isunusual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.unusualtype
     *
     * @return the value of orders.unusualtype
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getUnusualtype() {
        return unusualtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.unusualtype
     *
     * @param unusualtype the value for orders.unusualtype
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUnusualtype(String unusualtype) {
        this.unusualtype = unusualtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cid
     *
     * @return the value of orders.cid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cid
     *
     * @param cid the value for orders.cid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paytime
     *
     * @return the value of orders.paytime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paytime
     *
     * @param paytime the value for orders.paytime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderstatus
     *
     * @return the value of orders.orderstatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderstatus
     *
     * @param orderstatus the value for orders.orderstatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.isdelete
     *
     * @return the value of orders.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.isdelete
     *
     * @param isdelete the value for orders.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

	@Override
	public String toString() {
		return "Orders [bed=" + bed + ", oid=" + oid + ", onum=" + onum + ", bid=" + bid + ", actualpay=" + actualpay
				+ ", paystatus=" + paystatus + ", ordertime=" + ordertime + ", returntime=" + returntime
				+ ", isunusual=" + isunusual + ", unusualtype=" + unusualtype + ", cid=" + cid + ", paytime=" + paytime
				+ ", orderstatus=" + orderstatus + ", isdelete=" + isdelete + "]";
	}

}