package com.woniu.entity;

public class Photo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.pid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer fid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.url
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.pid
     *
     * @return the value of photo.pid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.pid
     *
     * @param pid the value for photo.pid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.fid
     *
     * @return the value of photo.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.fid
     *
     * @param fid the value for photo.fid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.url
     *
     * @return the value of photo.url
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.url
     *
     * @param url the value for photo.url
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUrl(String url) {
        this.url = url;
    }
}