package com.woniu.entity;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Trouble {
	
	
	
	@Override
	public String toString() {
		return "Trouble [hospital=" + hospital + ", tid=" + tid + ", ttitle=" + ttitle + ", tdescribe=" + tdescribe
				+ ", ttype=" + ttype + ", tdeclarant=" + tdeclarant + ", declarantphone=" + declarantphone + ", bid="
				+ bid + "]";
	}


	private String hospital;
	
	public final String getHospital() {
		return hospital;
	}


	public final void setHospital(String hospital) {
		this.hospital = hospital;
	}


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.tid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.ttitle
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String ttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.tdescribe
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String tdescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.ttype
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String ttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.tdeclarant
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String tdeclarant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.declarantphone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String declarantphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.tstatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Boolean tstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.tdeclaretime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Date tdeclaretime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.bid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.isdeclare
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Boolean isdeclare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trouble.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.tid
     *
     * @return the value of trouble.tid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.tid
     *
     * @param tid the value for trouble.tid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.ttitle
     *
     * @return the value of trouble.ttitle
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getTtitle() {
        return ttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.ttitle
     *
     * @param ttitle the value for trouble.ttitle
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTtitle(String ttitle) {
        this.ttitle = ttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.tdescribe
     *
     * @return the value of trouble.tdescribe
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getTdescribe() {
        return tdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.tdescribe
     *
     * @param tdescribe the value for trouble.tdescribe
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTdescribe(String tdescribe) {
        this.tdescribe = tdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.ttype
     *
     * @return the value of trouble.ttype
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getTtype() {
        return ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.ttype
     *
     * @param ttype the value for trouble.ttype
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTtype(String ttype) {
        this.ttype = ttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.tdeclarant
     *
     * @return the value of trouble.tdeclarant
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getTdeclarant() {
        return tdeclarant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.tdeclarant
     *
     * @param tdeclarant the value for trouble.tdeclarant
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTdeclarant(String tdeclarant) {
        this.tdeclarant = tdeclarant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.declarantphone
     *
     * @return the value of trouble.declarantphone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getDeclarantphone() {
        return declarantphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.declarantphone
     *
     * @param declarantphone the value for trouble.declarantphone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setDeclarantphone(String declarantphone) {
        this.declarantphone = declarantphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.tstatus
     *
     * @return the value of trouble.tstatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Boolean getTstatus() {
        return tstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.tstatus
     *
     * @param tstatus the value for trouble.tstatus
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTstatus(Boolean tstatus) {
        this.tstatus = tstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.tdeclaretime
     *
     * @return the value of trouble.tdeclaretime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getTdeclaretime() {
    	SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
        return fmt.format(tdeclaretime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.tdeclaretime
     *
     * @param tdeclaretime the value for trouble.tdeclaretime
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setTdeclaretime(Date tdeclaretime) {
        this.tdeclaretime = tdeclaretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.bid
     *
     * @return the value of trouble.bid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.bid
     *
     * @param bid the value for trouble.bid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.isdeclare
     *
     * @return the value of trouble.isdeclare
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Boolean getIsdeclare() {
        return isdeclare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.isdeclare
     *
     * @param isdeclare the value for trouble.isdeclare
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdeclare(Boolean isdeclare) {
        this.isdeclare = isdeclare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trouble.isdelete
     *
     * @return the value of trouble.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trouble.isdelete
     *
     * @param isdelete the value for trouble.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}