package com.woniu.entity;

import java.util.List;

public class Userinfo {

	private List<Tree> trees;
	public List<Tree> getTrees() {
		return trees;
	}
	public void setTrees(List<Tree> trees) {
		this.trees = trees;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.upass
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String upass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.wechat
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.pid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uid
     *
     * @return the value of userinfo.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uid
     *
     * @param uid the value for userinfo.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uname
     *
     * @return the value of userinfo.uname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uname
     *
     * @param uname the value for userinfo.uname
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.upass
     *
     * @return the value of userinfo.upass
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.upass
     *
     * @param upass the value for userinfo.upass
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUpass(String upass) {
        this.upass = upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.isdelete
     *
     * @return the value of userinfo.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.isdelete
     *
     * @param isdelete the value for userinfo.isdelete
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.wechat
     *
     * @return the value of userinfo.wechat
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.wechat
     *
     * @param wechat the value for userinfo.wechat
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.pid
     *
     * @return the value of userinfo.pid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.pid
     *
     * @param pid the value for userinfo.pid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}