package com.woniu.entity;

public class UserinforoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinforole.rid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinforole.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinforole.rid
     *
     * @return the value of userinforole.rid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinforole.rid
     *
     * @param rid the value for userinforole.rid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinforole.uid
     *
     * @return the value of userinforole.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinforole.uid
     *
     * @param uid the value for userinforole.uid
     *
     * @mbggenerated Mon Aug 19 15:25:36 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}